version: '3.1'

services:
  db:
    image: mysql:5.7-oracle
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: stuq_db
      MYSQL_USER: stuq_be
      MYSQL_PASSWORD: db_user_pass
      MYSQL_ROOT_PASSWORD: db_root_pass

  backend:
    build: backend/
    restart: always
    ports:
      - 8085:8080
    environment:
      DB_URL: jdbc:mysql://db:3306/stuq_db
      DB_USERNAME: stuq_be
      DB_PASSWORD: db_user_pass
      CORS: http://localhost:8080
    depends_on:
      - db
    labels:
      docker-compose-watcher.path: "backend/"

  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile-dev
    volumes:
      - ./frontend:/app
    restart: always
    ports:
      - 8080:8080

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 7000:80
    environment:
      PMA_HOST: db
