FROM node:lts-alpine
WORKDIR /app
RUN npm install -g @vue/cli

ENV NODE_ENV=development \
    VUE_APP_DEV_API_ENDPOINT="http://localhost:8085"

COPY package-lock.json package.json node_modules* /app/
RUN npm install

COPY ./ /app

CMD ["npm", "run", "serve"]
